[package]
name = "learn-rust-rig"
version = "0.1.0"
edition = "2021"

[dependencies]
rig-core = "0.6.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1.0.134"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "1.0.69"
